name: Helix Nightly
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-helix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: cgr.dev/chainguard/wolfi-base:latest
    steps:
      - name: Install and Build
        run: |
          apk add build-base rust git gh
          git clone https://github.com/helix-editor/helix.git
          cd helix
          cargo install --path helix-term --locked

      - name: upload to nightly release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload nightly ~/.cargo/bin/hx --clobber -R kranurag7/nightly-helix # overwrites
